### PR TITLE
Support writing multi-harmonic phasors to OME-TIFF

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This PR proposes the following changes:

- Add functions to write and read multi-harmonic phasor coordinates to [OME-TIFF](https://ome-model.readthedocs.io/en/stable/ome-tiff/): `phasor_to_ometiff` and `phasor_from_ometiff`.
- Remove outdated `read_ometiff_phasor` and `write_ometiff_phasor` functions.
- Add "Store phasor coordinates" section to introduction tutorial.
- Use `mean`, `real`, `imag`, `phase`, and `modulation` as coordinate names instead of `dc`, `re`, `im`, `ph`, `md`. 
- Improve documentation for `io` module.
- Require tifffile >= 2024.8.24 for `write_ometiff_phasor`.

The main purpose of the new functions is to export phasor coordinates for reading via Bio-Formats into Fiji, Matlab, and other software. It is not meant as a long-term storage solution for the many limitations.

The format has the following limitations and characteristics:

- The [OME model](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html) has no dimension dedicated to representing phasor coordinates. Possible ways to work around are to store phasor coordinates as:
  - complex numbers: requires transposition, which is resource intensive. Not supported by many software, including Fiji (?).
  - TIFF samples: requires transposition. Samples are merged with channels in the OME model.
  - ["Other" dimension](https://ome-model.readthedocs.io/en/latest/developers/6d-7d-and-8d-storage.html) `Q`: shows in Fiji as T, Z, or C. Fiji will not recognize QTZCYX images. This option is implemented.
- The OME model has no predefined option to store frequencies or specify harmonics. The options are to store those metadata as:
   - StructuredAnnotations or ModuloAlong labels: not available in Fiji or tifffile. Requires parsing XML to extract.
   - separate one-pixel or line image series: This option is implemented.
- OME-TIFF is an image format. Scalars and 1D data coordinate arrays are read back as 2D arrays.
- The phasor coordinates, mean, real, and imag, are stored as separate OME image series.
- Multi-harmonic phasor coordinates are transparently handled.
- Phasor coordinates are stored as `float32` (6 digits of precision) by default to maximize compatibility with Fiji and save storage space.
- Images larger than (1024, 1024) are stored as (256, 256) tiles, datasets larger than 2 GB as BigTIFF, and datasets larger than 8 KB zlib-compressed.
- The format does not allow to store phasor coordinates used for calibration. That would complicate the API. Use a separate file instead.
- No metadata other than the fundamental frequency and harmonics are stored. It would be nice to be able to store at least a comment string in the OME annotations. This should first be implemented in tifffile.
- The implementation and API are not suitable for handling images that do not comfortably fit in RAM. Currently a copy of all arrays is made in memory. 
- SimFCS will not be able to import the format. Should we add a `phasor_to_simfcs_ref` function later? How does SimFCS handle NaN? Is SimFCS still used?

For long term storage of phasor coordinates, other options may be better suited than OME-TIFF:

- [HDF5](https://www.hdfgroup.org/solutions/hdf5/): More versatile than OME-TIFF. Supports any dimensions. Easier metadata handling. Easier to read from Matlab and other programming languages. See also [Photon-HDF5](https://github.com/Photon-HDF5/photon-hdf5).
- [OME-ZARR/NGFF](https://github.com/ome/ngff): made for huge datasets. Ongoing work to [support FLIM](https://forum.image.sc/t/online-meeting-a-zarr-based-format-for-flim-raw-data/99244).

It might make sense to later move the `phasor_to_ometiff` and `phasor_from_ometiff` functions to the phasor module or main namespace (?)

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Support writing multi-harmonic phasors to OME-TIFF
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [x] New dependencies are explained.
- [x] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [x] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [x] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [x] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by cgohlke** [comment]
This is the "Bio-Formats Series Options" dialog that opens when dragging the file `phasors.ome.tiff` (written in the introductory tutorial) onto Fiji:

image

**Comment by bruno-pannunzio** [comment]
Hi @cgohlke, you read my mind! Last week I was working on the napari plugin that uses phasorpy and I came across to the problem of not being able to easily store and read multi harmonic images. One workaround I found was to expand de dimensions of the `mean` to match the `real` and `imag` before saving the image, but this was obviously not ideal, so I was going to discuss this with you in the next meeting or open a new issue. 

This is great, I believe as you pointed out, using this has it's advantages and disadvantages, as everything. But for the moment I think this works great. It's good to also be able to store the frequency and harmonic information in the file. 

> * SimFCS will not be able to import the format. Should we add a `phasor_to_simfcs_ref` function later? How does SimFCS handle NaN? Is SimFCS still used?

I think for now SimFCS is widely used because there are not so many available options, but eventually it will be less and less used. But I believe it would be nice to have a `phasor_to_simfcs_ref` since not all functionalities of SimFCS are available in PhasorPy and this will expand the options. Also, it would be nice to have this to compare with SimFCS results and validate our functions in some cases. 

> It might make sense to later move the `phasor_to_ometiff` and `phasor_from_ometiff` functions to the phasor module or main namespace (?)

This makes sense I think. Even more if they are named `phasor_*_ometiff` as it already matches the nomenclature for the `phasor` module. Also, in this case maybe the `io` module can be renamed? Since there will not be any output functions.

> * [OME-ZARR/NGFF](https://github.com/ome/ngff): made for huge datasets. Ongoing work to [support FLIM](https://forum.image.sc/t/online-meeting-a-zarr-based-format-for-flim-raw-data/99244).

This is a very interesting option. A couple of weeks ago, we were discussing this with @zoccoler and he suggested using OME-ZARR for several reasons, and he has been using it for his own packages. Maybe we can get some input on this from him and other community members.

**Comment by cgohlke** [comment]
>  it would be nice to have a phasor_to_simfcs_ref since not all functionalities of SimFCS are available in PhasorPy

OK, I will add `phasor_*_simfcs_ref` functions in another PR. The format only supports square images (and SimFCS prefers 256x256), so the export will produce many files in many cases.

> suggested using OME-ZARR for several reasons

In my opinion, multi-file formats are not a good choice for simple use cases. It's good for cloud storage, out-of-core processing, and maybe for sharing with napari if they support it. Still, there is no format that has proper metadata support for storing the results of Fourier transform from FLIM.

> Maybe we can get some input on this from him

Yes, I was thinking the same. Are you still in contact?

**Comment by cgohlke** [comment]
>> It might make sense to later move the phasor_to_ometiff and phasor_from_ometiff functions to the phasor module or main namespace (?)

> This makes sense I think. Even more if they are named phasor_*_ometiff as it already matches the nomenclature for the phasor module. Also, in this case maybe the io module can be renamed? Since there will not be any output functions.

Two things: the file io functions depend on xarray, which should be defer-imported if the functions are moved to another module. `io` is a common namespace for file handling functions (e.g. `scipy.io` and `skimage.io`). I think we should keep it.

**Review by bruno-pannunzio — APPROVED** [review]

**Comment by bruno-pannunzio** [comment]
Hi @cgohlke! While working on the napari plugin I was thinking it would be good to have a flag in the exported 'OME-TIFF' to check if the file was calibrated or not, maybe something like the frequency and harmonic information. Do you think this is worth it or it messes the exported file?

**Pull request merged**
