### PR TITLE
Add phasor_at_harmonic function

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This PR adds a convenience function, `phasor_at_harmonic`, which calculates, given the real component of phasor coordinates of a single exponential lifetime at a certain harmonic, the phasor coordinates at other harmonics. It is implemented as a numpy ufunc in Cython.

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Add phasor_at_harmonic function
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [x] New dependencies are explained.
- [x] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [x] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [x] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [ ] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by cgohlke** [comment]
Hi @bruno-pannunzio . This implements the `phasor_at_harmonic` convenience function we discussed by email.

**Review by bruno-pannunzio — COMMENTED** [review]
Thanks @cgohlke ! I tested it and works as expected and it also simplifies the workflow compared to only working with `phasor_form_lifetime` at multiple frequencies. 

I know that it is in the description of the function that works with phasors at the semicircle and that later in the `real` parameter it is stated that it must be monoexponential, but I feel it may lead up to some confusion and someone will try to use it for multi-exponential phasors as they may think the function is for other uses due to the given name. Maybe add a short line in the description also that it will only work with single exponential phasors?

**Comment by cgohlke** [comment]
Thanks for testing. I think you are right, there should be a sentence or two describing in little more detail. 

What about the function name, `phasor_at_harmonic`? I couldn't come up with anything better...

**Comment by bruno-pannunzio** [comment]
I thought about the name of the function but also couldn't think of a better one without it being too long. I think we can use this and maybe add a check to see if the phasor is located at the semicircle and if not raise an error?

**Comment by cgohlke** [comment]
> maybe add a check to see if the phasor is located at the semicircle and if not raise an error?

Note that the function only takes the real part of the phasor coordinates as an input. The imaginary part is implied, assumed to be on the semicircle.

**Review by bruno-pannunzio — APPROVED** [review]
You're right. Then I think the users should use it with caution, but now the description is very explicit on the subject, so it should be OK.

**Pull request merged**
