### PR TITLE
Add phasor_from_signal function (alternative to #20)

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This is an alternative to #20.

This PR adds a ``phasor_from_signal`` function based on the ``phasor_from_signal_f1`` implementation:

- Add option to specify one or more harmonics.
- Support ``int8`` and ``int64`` input.
- Add ``phasor_from_signal_fft`` reference implementation.
- Add tutorial comparing performance of the two implementations.
- Remove ``phasor_from_signal_f1``.

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Add phasor_from_signal function
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [x] New dependencies are explained.
- [x] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [x] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [x] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [x] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by cgohlke** [comment]
Apparently the results of FFT for edge cases are platform dependent. One more reason to avoid using FFT.

**Comment by bruno-pannunzio** [comment]
I think this is a good idea, as this improves many aspects of the phasor calculation compared to the fft. I also think we should keep the fft implementation as you did in `phasor_from_signal_fft` in case someone needs that. 

I was thinking if it would be a good idea to allow to pass the harmonic as a range or a set of harmonic numbers, in the case that more than one harmonic is needed, it is computed and returned by the same function, instead of habing to compute and store each one separately. Do you think this can be useful?

**Comment by cgohlke** [comment]
> I was thinking if it would be a good idea to allow to pass the harmonic as a range or a set of harmonic numbers

Good idea. Let me add that.

**Comment by schutyb** [comment]
> > I was thinking if it would be a good idea to allow to pass the harmonic as a range or a set of harmonic numbers
> 
> Good idea. Let me add that.

The spectral unmixing we did we use many harmonics, so if you do that do I use it, I was using the fft outputs. Also we know a priri how many harmonic we need. 

One question, I tested phasor_from_signal and the fft version using module **time** to see how much time does it takes to excecute,  using the same sinteticc data, is it the correct way to test the execution time or there is a better one?

**Comment by cgohlke** [comment]
I added options to 

- calculate phasor coordinates for multiple harmonics at once 
- specify drop-in replacement functions for `numpy.fft.fft`

Here are the benchmark results (absolute and relative duration) for a `(384, 384, 384)` `uint16` stack on my system:
```
harmonics 1
  axis -1
    phasor_from_signal       0.034s   1.00
      threads 8              0.006s   0.19
    phasor_from_signal_fft   0.346s  10.13
      scipy_fft              0.387s  11.34
      mkl_fft                0.166s   4.87
  axis 0
    phasor_from_signal       0.144s   4.21
      threads 8              0.031s   0.91
    phasor_from_signal_fft   2.219s  64.99
      scipy_fft              0.907s  26.56
      mkl_fft                0.191s   5.60
  axis 2
    phasor_from_signal       0.036s   1.07
      threads 8              0.007s   0.21
    phasor_from_signal_fft   0.350s  10.26
      scipy_fft              0.384s  11.25
      mkl_fft                0.163s   4.79
harmonics 8
  axis -1
    phasor_from_signal       0.279s   8.16
      threads 8              0.042s   1.22
    phasor_from_signal_fft   0.368s  10.79
      scipy_fft              0.403s  11.80
      mkl_fft                0.177s   5.19
  axis 0
    phasor_from_signal       1.108s  32.46
      threads 8              0.312s   9.14
    phasor_from_signal_fft   2.240s  65.62
      scipy_fft              0.921s  26.99
      mkl_fft                0.196s   5.75
  axis 2
    phasor_from_signal       0.270s   7.90
      threads 8              0.040s   1.17
    phasor_from_signal_fft   0.360s  10.56
      scipy_fft              0.402s  11.77
      mkl_fft                0.183s   5.36
```

**Comment by cgohlke** [comment]
> One question, I tested phasor_from_signal and the fft version using module time to see how much time does it takes to excecute, using the same sinteticc data, is it the correct way to test the execution time or there is a better one?

[time.perf_counter](https://docs.python.org/3/library/time.html#time.perf_counter) should be OK. The tutorial uses the [timeit](https://docs.python.org/3/library/timeit.html) module. There's may other options.

**Comment by bruno-pannunzio** [comment]
Hi @cgohlke, this is amazing, nice implementations and the tutorials are also very clear. The results from the benchmarks are amazing and show quite clear that for smaller harmonics, it's best to use your cython implementation, but for higher harmonics it's not so clear, so it's good to have both possibilities. Regarding this, do you think that the default function for the `phasor_from_signal_fft`should be the `mkl_fft` instead of numpy's? It seemed much faster for small and large harmonic numbers. but I don't know if it has a downside of using it. Is the mkl_fft optimized for Intel CPU's? If that is the case, maybe we should stick with numpy's fft. 

I am not sure if I understood the use of `sample_phase`parameter in `pasor_from_signal`, but I am guessing it is used to cover some cases were samples are not equally spaced.

**Review by bruno-pannunzio — APPROVED** [review]

**Comment by cgohlke** [comment]
>  do you think that the default function for the phasor_from_signal_fft should be the mkl_fft instead of numpy's

Probably not: `mkl_fft ` is optimized for Intel CPUs but also works well on AMD. It won't work on ARM, like Apple M#. Also, the [MKL runtime](https://pypi.org/project/mkl/) package is quite large (~200 MB compressed). Finally, MKL is free but not open source.

I have used Intel MKL in the past for the [ICSx64.dll](https://github.com/cgohlke/icsdll/) for SimFCS. It's really fast and nice to work with.

It might be worth adding a function that works with [CuPy](https://github.com/cupy/cupy)/CUDA. For really large images that could be the fastest.

> I am not sure if I understood the use of `sample_phase` parameter in `pasor_from_signal`

In real-time, homodyne, frequency-domain measurements, we sometimes acquired images at phases that are not linear increasing but in a certain order to minimize the effects of bleaching.

The function might also be useful for working with sin/cos filters but I have not looked into that.

**Comment by cgohlke** [comment]
Downloads from Zenodo are frequently failing today, again...

**Comment by cgohlke** [comment]
For comparison, here are the timings on a M2 Mac mini:
```
harmonics 1
  axis -1
    phasor_from_signal       0.059s   1.00
    phasor_from_signal_fft   0.284s   4.79
      scipy_fft              0.298s   5.02
  axis 0
    phasor_from_signal       0.068s   1.14
    phasor_from_signal_fft   1.065s  17.95
      scipy_fft              0.421s   7.09
  axis 2
    phasor_from_signal       0.059s   0.99
    phasor_from_signal_fft   0.285s   4.80
      scipy_fft              0.301s   5.08
harmonics 8
  axis -1
    phasor_from_signal       0.467s   7.86
    phasor_from_signal_fft   0.299s   5.04
      scipy_fft              0.318s   5.36
  axis 0
    phasor_from_signal       0.541s   9.11
    phasor_from_signal_fft   1.064s  17.94
      scipy_fft              0.425s   7.16
  axis 2
    phasor_from_signal       0.467s   7.86
    phasor_from_signal_fft   0.300s   5.05
      scipy_fft              0.318s   5.36
```

**Comment by schutyb** [comment]
> I added options to
> 
> * calculate phasor coordinates for multiple harmonics at once
> * specify drop-in replacement functions for `numpy.fft.fft`
> 
> Here are the benchmark results (absolute and relative duration) for a `(384, 384, 384)` `uint16` stack on my system:
> 
> ```
> harmonics 1
>   axis -1
>     phasor_from_signal       0.034s   1.00
>       threads 6              0.006s   0.17
>     phasor_from_signal_fft   0.347s  10.22
>       scipy_fft              0.395s  11.62
>       mkl_fft                0.160s   4.71
>   axis 0
>     phasor_from_signal       0.162s   4.77
>       threads 6              0.037s   1.10
>     phasor_from_signal_fft   2.236s  65.80
>       scipy_fft              0.922s  27.14
>       mkl_fft                0.195s   5.73
>   axis 2
>     phasor_from_signal       0.037s   1.09
>       threads 6              0.008s   0.22
>     phasor_from_signal_fft   0.360s  10.60
>       scipy_fft              0.395s  11.62
>       mkl_fft                0.169s   4.98
> harmonics 8
>   axis -1
>     phasor_from_signal       0.281s   8.26
>       threads 6              0.046s   1.35
>     phasor_from_signal_fft   0.367s  10.79
>       scipy_fft              0.410s  12.06
>       mkl_fft                0.180s   5.31
>   axis 0
>     phasor_from_signal       1.211s  35.63
>       threads 6              0.345s  10.16
>     phasor_from_signal_fft   2.263s  66.58
>       scipy_fft              0.936s  27.54
>       mkl_fft                0.200s   5.89
>   axis 2
>     phasor_from_signal       0.284s   8.37
>       threads 6              0.046s   1.34
>     phasor_from_signal_fft   0.377s  11.10
>       scipy_fft              0.431s  12.69
>       mkl_fft                0.185s   5.44
> ```

This is what I get in  macos M1 pro 



```
harmonics 1
  axis -1
    phasor_from_signal       0.089s   1.00
      threads 4              0.083s   0.93
    phasor_from_signal_fft   0.486s   5.46
  axis 0
    phasor_from_signal       0.100s   1.12
      threads 4              0.099s   1.11
    phasor_from_signal_fft   1.457s  16.35
  axis 2
    phasor_from_signal       0.083s   0.93
      threads 4              0.083s   0.93
    phasor_from_signal_fft   0.398s   4.46
harmonics 8
  axis -1
    phasor_from_signal       0.658s   7.39
      threads 4              0.658s   7.39
    phasor_from_signal_fft   0.420s   4.71
  axis 0
    phasor_from_signal       0.782s   8.78
      threads 4              0.756s   8.49
    phasor_from_signal_fft   1.367s  15.34
  axis 2
    phasor_from_signal       0.657s   7.38
      threads 4              0.658s   7.39
    phasor_from_signal_fft   0.417s   4.69
```

**Pull request merged**
