### PR TITLE
Enable mypy strict mode

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This PR enables stricter `mypy` checks and also tunes some `pre-commit` and `pytest` settings (follow-up #114):

- Enable mypy [strict](https://mypy.readthedocs.io/en/stable/command_line.html#miscellaneous-strictness-flags) and [warn-unreachable](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable) flags.
- Exclude `phasorpy._phasorpy` and some third party packages from mypy.
- Fix errors in mypy strict mode (mostly missing types and `ignore[no-any-return]`).
- Use https://github.com/psf/black-pre-commit-mirror because it's faster.
- Do not allow prettier to always change line endings on Windows.
- Configure pre-commit.ci.
- Enable pytest to raise errors on deprecation warnings.
- Disable static code analysis on Python 3.10 because mypy strict mode fails with old dependencies.
- On macOS, skip failing tests of unused `_blend_darken` and `_blend_lighten` functions.

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Enable mypy strict mode
```

## Checklist

- [ ] The pull request title, summary, and description are concise.
- [ ] Related issues are linked in the description.
- [ ] New dependencies are explained.
- [ ] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [ ] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [ ] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [ ] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [ ] New features are covered in tutorials.
- [ ] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by cgohlke** [comment]
Hi @bruno-pannunzio : are you using a Mac? Do you have any idea why the `_blend_darken` and `_blend_lighten` Cython functions emit `RuntimeWarning: invalid value encountered`? Did you notice this on your system before? On Ubuntu and Windows no warnings are raised as expected. Those functions are checking for NaN input, just like the other Cython ufuncs do. We can probably mark the failing tests as xfail on macOS. What do you think?

**Comment by cgohlke** [comment]
Since `_blend_darken` and `_blend_lighten` are not used in PhasorPy, I disabled the failing tests on macOS. Probably XCode erroneously optimizes the `isnan` checks away.

The decreased test coverage is due to an increase in lines of code for typing, which is not tested.

**Comment by bruno-pannunzio** [comment]
Hi @cgohlke. I have no warnings running `_blend_darken` and `_blend_lighten` in my Mac. Also tests are not failing. I am not aware what this problem might lie.

I think we can skip those tests for Mac as you already did.

**Review by bruno-pannunzio — APPROVED** [review]

**Comment by cgohlke** [comment]
Hi @bruno-pannunzio : thanks for checking. I suspect it is a compiler optimization issue. GitHub Actions might have an older XCode version installed and it looks like this is fixed in the latest version.

**Comment by cgohlke** [comment]
This seems like a good time to revisit the [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=phasorpy%2Fphasorpy&branch=main) from the Scientific Python Library Development Guide.

- They want `ruff` and `mypy` enabled in `pre-commit`. We discussed and postponed both.

- They suggest enabling `enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]` for mypy. I'll look into that. 

- Instead of `blacken-docs` we use `blackdoc`.

- I do not agree on using either `ReadTheDocs` or a task runner. 

- Not sure why they recommend setting a custom pre-commit CI message. The default "[pre-commit.ci] pre-commit autoupdate" looks better than the replacement they suggest. 

- The "upload-artifact" detection looks too strict on their side. We should update or replace the outdated `release-pypi.yml` before the release though.

@bruno-pannunzio : Any thoughts?

**Comment by cgohlke** [comment]
> you don't want to use ReadTheDocs to avoid duplicating documentation or is there another reason?

They insert Ads.

> I am not aware of the benefits of using the suggested format for using unique names for "upload-artifact"

I think they are referring to upload-artifact@v4, which requires unique names. Anyway, we already use unique upload names in the wheel builder (release-pypi.yml is outdated):

https://github.com/phasorpy/phasorpy/blob/7d845ea0d170d921739b93a204a8fe16c69ef059/.github/workflows/build_wheels.yml#L34-L37

**Comment by bruno-pannunzio** [comment]
Excellent, I totally agree. I then believe that we are covered regarding the Scientific Python Library and have deliberately made the modifications we think are better, at least for now. But maybe it's a good idea to revisit this with some regularity to make sure everything and we are aligned.

**Comment by cgohlke** [comment]
> maybe it's a good idea to revisit this with some regularity

Good idea. I opened issue #118 as a reminder.

**Pull request merged**
