### PR TITLE
Add interactive FRET phasor plot

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This PR proposes the following changes:

- add a `PhasorPlotFret` class, which plots FRET efficiency trajectories of donor and acceptor channels in phasor space. The class can be run in interactive mode, using matplotlib slider widgets to control FRET model parameters.

- add a command line option to run `PhasorPlotFret` in interactive mode: `python -m phasorpy fret`

- simplify the `phasorpy_fret.py` tutorial using `PhasorPlotFret`. Mark the actual phasor coordinates of the donor and acceptor channels.

- add a mouse cursor callback function to `PhasorPlot`, which displays (in the matplotlib toolbar) polar coordinates and apparent lifetimes (if possible) in addition to phasor coordinates.

- rename `acceptor_excitation` to `acceptor_bleedthrough`.

- change the definition of `donor_bleedthrough`, `acceptor_excitation`, `acceptor_background`, and `donor_background` of the FRET model to weights relative to the fluorescence of the acceptor at 100% energy transfer respectively donor at 0% energy transfer.

- add some cross references to docstrings.

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Add interactive FRET phasor plot
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [x] New dependencies are explained.
- [x] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [x] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [x] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [x] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by bruno-pannunzio** [comment]
Hi @cgohlke, this looks very nice. I have been trying to run the interactive option from the command line but I keep getting this error:
`ImportError: cannot import name '_phasor_from_fret_acceptor' from 'phasorpy._phasor'`
I am also getting this error when creating the tutorials.

**Comment by cgohlke** [comment]
> `ImportError: cannot import name '_phasor_from_fret_acceptor' from 'phasorpy._phasor'`

Whenever `_phasor.pyx` changes you have to rebuild the C extension. Try `python -m pip install -e .` or `python setup.py build_ext --inplace`.

**Comment by bruno-pannunzio** [comment]
Oh, I wasn't aware that need to be built each time Cython is modified. That worked and now I was able to run it correctly. 

The interactive FRET plot is very nice! Also the implementation of `PhasorPlotFret` does help a lot with the tutorial by making it clear and easier to follow, so I think it is a good idea, also thinking in future developments, not to overload the `PhasorPlot` and making it more personalized for the application. 

The interactive mode is great! I think it would be a good idea to implement it also for the `PhasorPlot` class and also the `plot_phasor` function, at least. For now just the mouse cursor you implemented is useful in the interactive mode, but for future developments, the interactive mode will be of much use and I think it is great if we can already make it work like that. Maybe if you believe this is not for this PR we can think of it for another one.

**Review by bruno-pannunzio — APPROVED** [review]

**Comment by cgohlke** [comment]
> I think it would be a good idea to implement it also for the PhasorPlot class 

Can you explain what interactive features could be implemented for the `PhasorPlot` class?

**Pull request merged**
