### PR TITLE
Add geometric helper functions

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This PR adds geometric helper functions and addresses some issues and ideas raised during the discussion of #79, specifically https://github.com/phasorpy/phasorpy/pull/79#issuecomment-2214649876:

- Implement useful geometry functions as private ufuncs in the Cython module:

  - `_distance_from_line`
  - `_distance_from_point`
  - `_distance_from_segment`
  - `_fraction_on_line`
  - `_fraction_on_segment`
  - `_intersection_circle_circle`
  - `_intersection_circle_line`
  - `_is_inside_circle`
  - `_is_inside_ellipse` and `_is_inside_ellipse_`
  - `_is_inside_polar_rectangle`
  - `_is_inside_range`
  - `_is_inside_rectangle`
  - `_is_inside_stadium`, same as `_is_near_segment`
  - `_is_near_line`
  - `_point_on_line`
  - `_point_on_segment`
  - `_segment_direction_and_length`

- Above ufuncs replace several helper functions from the `_utils` module (the tests were migrated):

  - `project_phasor_to_line` -> `_point_on_segment and _point_on_line`
  - `line_from_components` -> `_segment_direction_and_length`
  - `mask_cursor` -> `_is_inside_circle`
  - `mask_segment` -> `_is_inside_stadium`
  - `circle_circle_intersection` -> `_intersection_circle_circle`
  - `circle_line_intersection` -> `_intersection_circle_line`

- Remove second component output array from `two_fractions_from_phasor` since it can easily be calculated from the first component.

- Reimplement `two_fractions_from_phasor` as a thin wrapper of `_fraction_on_segment`.
- Remove `fractions` output from `graphical_component_analysis` and replace the `steps` parameter with `fractions`, which can be the number of equidistant fractions or an array of fraction values.
- Use `_is_inside_circle` and `_is_inside_stadium` ufuncs in `graphical_component_analysis`.

- Improve the components tutorial:
  
  - add example of graphical solution for two components.
  - shorten animation code.
  - prefer `PhasorPlot` methods over matplotlib.
  - improve consistency.

- Make the `PhasorPlot.plot` `fmt` parameter position only in accordance with matplotlib.
- Add `PhasorPlot.dataunit_to_point` property to convert from data to point units.
- Add option to plot labels in `PhasorPlot.components`.

There are still many areas for improvement, which could be discussed and/or addressed in this or future PRs:

- [ ] The ufuncs are private, not part of the public API. The documentation could be improved if necessary.
- [ ] The `_is_*` functions currently return `int16` values instead of `bool` because of [issues in Cython](https://github.com/cython/cython/pull/6196#issuecomment-2209509572).
- [ ] The `_is_*` functions take a `mask` parameter, which is currently unused. It might or might not be useful in the future when combining masks.
- [x] The components tutorial uses the private `PhasorPlot._lines` property. Instead, the `PhasorPlot` methods could return artists if possible, just like matplotlib functions.
- [ ] We should review the default line properties used in `PhasorPlot.components` and `PhasorPlot.cursors`. Those methods frequently requires changing the parameter defaults.
- [ ] The `graphical_component_analysis` could be split into two functions, for two and three components. That could simplify the API and documentation for two components.
- [x] Is there a reference for the graphical component analysis that could be added to the documentation? Is there an optimal combination of step size and radius? It seems to me that the default of a 100 steps with a radius of 0.05 is oversampling?

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Add geometric helper functions
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [x] New dependencies are explained.
- [x] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [x] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [x] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [x] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by cgohlke** [comment]
To demonstrate some of the ufuncs on a grid of points:

ufunc

**Comment by cgohlke** [comment]
> There is a paper vaguely describing the procedure, but I think it should be mentioned. Where should I add the reference to the paper? As a Note in the docstring of the function?

The numpy docstring standard has a section for references: https://numpydoc.readthedocs.io/en/latest/format.html#references. Let me know the reference and I can add it to this PR, or you can add it later.

> I think it would be good if it returned the artist so we don't need to use PhasorPlot._lines. Also as currently the plot method doesn't return anything, I think it won't have much impact on other functions.

OK, I'll look into it. I remember there were reasons for not returning artists regarding typing, documentation, and noise in interactive use.

**Comment by bruno-pannunzio** [comment]
> The numpy docstring standard has a section for references: https://numpydoc.readthedocs.io/en/latest/format.html#references. Let me know the reference and I can add it to this PR, or you can add it later.

Excelent! This is the doi of the paper:

https://doi.org/10.1021/acs.jpca.9b07880

**Comment by cgohlke** [comment]
I added the reference for the graphical method and changed some PhasorPlot methods to return line artists.

**Comment by bruno-pannunzio** [comment]
@cgohlke I think it would be good to have these functionalities in the main to implement them in the masks functions. I think this is ready to be merged if you also think so.

**Comment by cgohlke** [comment]
> I think it would be good to have these functionalities in the main to implement them in the masks functions.

Yes, I'll add that to this PR.

**Comment by cgohlke** [comment]
>> I think it would be good to have these functionalities in the main to implement them in the masks functions.

> Yes, I'll add that to this PR.

Hi @bruno-pannunzio : the changes to the cursors module turned out to be extensive. I decided to propose them in a different PR. 

Can you review this PR and approve it if it looks OK?

**Pull request merged**
