### PR TITLE
Add LFD workshop FLIM tutorial

### PR DESCRIPTION
**Pull request by cgohlke**
## Description

This tutorial is a close adaptation of the [LFD Workshop computer training tutorial - FLIM section](https://www.lfd.uci.edu/workshop/2021/files/LFDWorkshop2021-ComputerTraining.pdf) (by E. Gratton, M. Digman, and J. Unruh) using the PhasorPy library instead of the [Globals for Images · SimFCS](https://www.lfd.uci.edu/globals/) and Excel software.

I was curious how much of the original tutorial could be implemented using the current state of the PhasorPy library. 

The following functionality is still missing from PhasorPy to finish the tutorial:

- [ ] synthesize time-domain signal (#6, #86)
- [ ] filtering, thresholding images (#85, #88)
- [ ] cursors (#48)
- [ ] component analysis (#47 and #59)

## Release note

Summarize the changes in the code block below to be included in the
[release notes](https://www.phasorpy.org/stable/release.html):

```release-note
Add LFD workshop FLIM tutorial
```

## Checklist

- [x] The pull request title, summary, and description are concise.
- [x] Related issues are linked in the description.
- [ ] New dependencies are explained.
- [ ] The source code and documentation can be distributed under the [MIT license](https://www.phasorpy.org/stable/license.html).
- [x] The source code adheres to [code standards](https://www.phasorpy.org/stable/contributing.html#code-standards).
- [ ] New classes, functions, and features are thoroughly [tested](https://www.phasorpy.org/stable/contributing.html#tests).
- [ ] New, user-facing classes, functions, and features are [documented](https://www.phasorpy.org/stable/contributing.html#documentation).
- [ ] New features are covered in tutorials.
- [x] No files other than source code, documentation, and project settings are added to the repository.

### CODE REVIEW

**Comment by bruno-pannunzio** [comment]
Excelent idea Christoph! This is very useful to see what vital aspects of the library are we missing. We can discuss today, but I think this is a very good starting point to think how to approach this missing functionalities and plan the next steps.

**Comment by lmalacrida** [comment]
Sounds very good and important. I will be happy to collaborate in testing and running the tutorial

**Comment by cgohlke** [comment]
A HTML version of the tutorial is available in the [artifact of the "Deploy documentation" checks](https://github.com/phasorpy/phasorpy/actions/runs/8873440270/artifacts/1455411222). Extract all the files in the archive to a directory and open `index.html` with a web browser. Then browse to `Tutorials` -> `LFD Workshop FLIM Tutorial`.

**Comment by cgohlke** [comment]
Could this PR be merged so it can be updated while adding new features in other PRs?

**Review by bruno-pannunzio — APPROVED** [review]
I agree @cgohlke, this can be merged so we can have it available and keep working on it as we keep implementing the missing features.

**Pull request merged**
